### ISSUE TITLE
关于WFST的解码

### ISSUE THREAD

**Issue by Sundy1219** [lifeiteng/codingmath#1]
你好，我在数字编程上看到你这篇博文《构建 CTC 语音识别解码网络》，在构建好解码图后，如何得到更加准确的输出呢？最后的利用解码图（fst)解码的具体过程是什么样的？
 “解码时从解码网络获得TransitionId转为对应的PdfId做为 RNN 输出层索引获得” ，我最想理解你这句话，发现看不懂
期待你的回复，谢谢

**Comment by lifeiteng** [comment]
可以参考kaldi-ctc decoding相关代码

在 2016年11月18日 上午9:01，Sundy1219 notifications@github.com写道：

**Comment by Sundy1219** [comment]
我只想看懂 生成fst后，接下去如何解码？大神，可以指点下吗？多谢
